### ISSUE TITLE
Create S3 Bucket and configure write access for Omer

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/iac#22]
Create a bucket to put binary files, zip files, etc that need to be published.

**Comment by angiedear** [comment]
Blocked by Scott with permissions issue

**Comment by scottdear** [comment]
1. Create bucket
2. Create policy w/ read/write access to bucket

**Comment by angiedear** [comment]
In progress

**Comment by angiedear** [comment]
In progress

**Comment by godslave05** [comment]
Again Stuck because of permission

I was trying to create policy by writing the json and get this error 


You need permissions
You do not have the permission required to perform this operation. Ask your administrator to add permissions.
User: arn:aws:iam::092537850698:user/asad is not authorized to perform: access-analyzer:ValidatePolicy on resource: arn:aws:access-analyzer:us-east-1:092537850698:*

**Comment by omerll** [comment]
@scottdear please help to resoolve permition issue

**Comment by godslave05** [comment]
The policy json
`{
    "Version": "2021-08-13",
    "Statement": [
                {
            "Effect": "Allow",
            "Action": [
              "s3:PutObject",
              "s3:GetObject",
              "s3:GetObjectVersion",
              "s3:DeleteObject",
              "s3:DeleteObjectVersion"
            ],
            "Resource": "arn:aws:s3:::seapod-bucket/*"
        },
        {
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::seapod-bucket"
        }
    ]
}`

**Comment by diegopau** [comment]
I am closing this. It is outdated, doesn't seem to be needed anymore
